"""adds category column to post and a default value of an empty string

Revision ID: 33bb7cceaf53
Revises: 5546ea4187da
Create Date: 2019-10-27 17:30:15.539781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bb7cceaf53'
down_revision = '5546ea4187da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
